// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testdata.proto

package maptester

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestValue struct {
	S                    string   `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	I                    int64    `protobuf:"varint,2,opt,name=i,proto3" json:"i,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestValue) Reset()         { *m = TestValue{} }
func (m *TestValue) String() string { return proto.CompactTextString(m) }
func (*TestValue) ProtoMessage()    {}
func (*TestValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c4782d007dfce9, []int{0}
}

func (m *TestValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestValue.Unmarshal(m, b)
}
func (m *TestValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestValue.Marshal(b, m, deterministic)
}
func (m *TestValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestValue.Merge(m, src)
}
func (m *TestValue) XXX_Size() int {
	return xxx_messageInfo_TestValue.Size(m)
}
func (m *TestValue) XXX_DiscardUnknown() {
	xxx_messageInfo_TestValue.DiscardUnknown(m)
}

var xxx_messageInfo_TestValue proto.InternalMessageInfo

func (m *TestValue) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func (m *TestValue) GetI() int64 {
	if m != nil {
		return m.I
	}
	return 0
}

type IntTestLine struct {
	Key                  []int64    `protobuf:"varint,1,rep,packed,name=key,proto3" json:"key,omitempty"`
	Value                *TestValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *IntTestLine) Reset()         { *m = IntTestLine{} }
func (m *IntTestLine) String() string { return proto.CompactTextString(m) }
func (*IntTestLine) ProtoMessage()    {}
func (*IntTestLine) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c4782d007dfce9, []int{1}
}

func (m *IntTestLine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntTestLine.Unmarshal(m, b)
}
func (m *IntTestLine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntTestLine.Marshal(b, m, deterministic)
}
func (m *IntTestLine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntTestLine.Merge(m, src)
}
func (m *IntTestLine) XXX_Size() int {
	return xxx_messageInfo_IntTestLine.Size(m)
}
func (m *IntTestLine) XXX_DiscardUnknown() {
	xxx_messageInfo_IntTestLine.DiscardUnknown(m)
}

var xxx_messageInfo_IntTestLine proto.InternalMessageInfo

func (m *IntTestLine) GetKey() []int64 {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *IntTestLine) GetValue() *TestValue {
	if m != nil {
		return m.Value
	}
	return nil
}

type StringTestLine struct {
	Key                  string     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *TestValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StringTestLine) Reset()         { *m = StringTestLine{} }
func (m *StringTestLine) String() string { return proto.CompactTextString(m) }
func (*StringTestLine) ProtoMessage()    {}
func (*StringTestLine) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c4782d007dfce9, []int{2}
}

func (m *StringTestLine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringTestLine.Unmarshal(m, b)
}
func (m *StringTestLine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringTestLine.Marshal(b, m, deterministic)
}
func (m *StringTestLine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringTestLine.Merge(m, src)
}
func (m *StringTestLine) XXX_Size() int {
	return xxx_messageInfo_StringTestLine.Size(m)
}
func (m *StringTestLine) XXX_DiscardUnknown() {
	xxx_messageInfo_StringTestLine.DiscardUnknown(m)
}

var xxx_messageInfo_StringTestLine proto.InternalMessageInfo

func (m *StringTestLine) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StringTestLine) GetValue() *TestValue {
	if m != nil {
		return m.Value
	}
	return nil
}

type MapTestResult struct {
	NbLines              int32    `protobuf:"varint,1,opt,name=nbLines,proto3" json:"nbLines,omitempty"`
	NbEntries            int32    `protobuf:"varint,2,opt,name=nbEntries,proto3" json:"nbEntries,omitempty"`
	NbSameKeys           int32    `protobuf:"varint,3,opt,name=nbSameKeys,proto3" json:"nbSameKeys,omitempty"`
	NbOfTimesSameKey     []int32  `protobuf:"varint,4,rep,packed,name=nbOfTimesSameKey,proto3" json:"nbOfTimesSameKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapTestResult) Reset()         { *m = MapTestResult{} }
func (m *MapTestResult) String() string { return proto.CompactTextString(m) }
func (*MapTestResult) ProtoMessage()    {}
func (*MapTestResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_40c4782d007dfce9, []int{3}
}

func (m *MapTestResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapTestResult.Unmarshal(m, b)
}
func (m *MapTestResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapTestResult.Marshal(b, m, deterministic)
}
func (m *MapTestResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapTestResult.Merge(m, src)
}
func (m *MapTestResult) XXX_Size() int {
	return xxx_messageInfo_MapTestResult.Size(m)
}
func (m *MapTestResult) XXX_DiscardUnknown() {
	xxx_messageInfo_MapTestResult.DiscardUnknown(m)
}

var xxx_messageInfo_MapTestResult proto.InternalMessageInfo

func (m *MapTestResult) GetNbLines() int32 {
	if m != nil {
		return m.NbLines
	}
	return 0
}

func (m *MapTestResult) GetNbEntries() int32 {
	if m != nil {
		return m.NbEntries
	}
	return 0
}

func (m *MapTestResult) GetNbSameKeys() int32 {
	if m != nil {
		return m.NbSameKeys
	}
	return 0
}

func (m *MapTestResult) GetNbOfTimesSameKey() []int32 {
	if m != nil {
		return m.NbOfTimesSameKey
	}
	return nil
}

func init() {
	proto.RegisterType((*TestValue)(nil), "maptester.TestValue")
	proto.RegisterType((*IntTestLine)(nil), "maptester.IntTestLine")
	proto.RegisterType((*StringTestLine)(nil), "maptester.StringTestLine")
	proto.RegisterType((*MapTestResult)(nil), "maptester.MapTestResult")
}

func init() {
	proto.RegisterFile("testdata.proto", fileDescriptor_40c4782d007dfce9)
}

var fileDescriptor_40c4782d007dfce9 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0x89, 0x71, 0x95, 0x9d, 0x6a, 0x29, 0xc1, 0x43, 0x0e, 0x22, 0xcb, 0x5e, 0x5c, 0x7a,
	0xd8, 0x83, 0x3e, 0x83, 0x07, 0xa9, 0x7f, 0x20, 0x2d, 0xde, 0x13, 0x1c, 0x25, 0xd8, 0x4d, 0x97,
	0x9d, 0xa9, 0xd0, 0xe7, 0xf0, 0x85, 0x65, 0x52, 0xad, 0x42, 0x4f, 0xbd, 0x65, 0x7e, 0xf9, 0xf2,
	0xfb, 0xc8, 0xc0, 0x98, 0x91, 0xf8, 0xd5, 0xb3, 0x6f, 0xfb, 0x61, 0xc5, 0x2b, 0x53, 0x76, 0xbe,
	0x17, 0x84, 0x43, 0x7d, 0x0d, 0xe5, 0x02, 0x89, 0x5f, 0xfc, 0x72, 0x8d, 0xe6, 0x0c, 0x14, 0x59,
	0x55, 0xa9, 0xa6, 0x74, 0x8a, 0x64, 0x8a, 0xf6, 0xa8, 0x52, 0x8d, 0x76, 0x2a, 0xd6, 0x33, 0x18,
	0xdd, 0x27, 0x96, 0xec, 0x43, 0x4c, 0x68, 0x26, 0xa0, 0x3f, 0x70, 0x63, 0x55, 0xa5, 0x1b, 0xed,
	0xe4, 0x68, 0xa6, 0x50, 0x7c, 0x8a, 0x25, 0x3f, 0x19, 0xdd, 0x5c, 0xb4, 0xbb, 0x92, 0x76, 0xd7,
	0xe0, 0xb6, 0x91, 0xfa, 0x09, 0xc6, 0x73, 0x1e, 0x62, 0x7a, 0xdf, 0xf7, 0x49, 0xf9, 0xc1, 0xbe,
	0x2f, 0x05, 0xe7, 0x8f, 0xbe, 0x17, 0xee, 0x90, 0xd6, 0x4b, 0x36, 0x16, 0x4e, 0x53, 0x10, 0xf3,
	0xf6, 0x43, 0x85, 0xfb, 0x1d, 0xcd, 0x25, 0x94, 0x29, 0xdc, 0x25, 0x1e, 0x22, 0x52, 0x76, 0x17,
	0xee, 0x0f, 0x98, 0x2b, 0x80, 0x14, 0xe6, 0xbe, 0xc3, 0x19, 0x6e, 0xc8, 0xea, 0x7c, 0xfd, 0x8f,
	0x98, 0x29, 0x4c, 0x52, 0x78, 0x7e, 0x5b, 0xc4, 0x0e, 0xe9, 0x07, 0xda, 0xe3, 0x4a, 0x37, 0x85,
	0xdb, 0xe3, 0xe1, 0x24, 0x6f, 0xfb, 0xf6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xf7, 0x0b, 0xc5,
	0x7f, 0x01, 0x00, 0x00,
}
